### ISSUE TITLE
Improper bounds-check on `LOADSP`

### ISSUE THREAD

**Issue by birb007** [yabits/ebcvm#44]
## Issue

From the UEFI specification, `LOADSP` has the behaviour that
>  Specifying a reserved dedicated register index results in an instruction encoding exception.

which is not properly validated; the bounds-check is always `false`. The instruction Operand 1 cannot be both below RV2 and above RV7 simultaneously. 
https://github.com/yabits/ebcvm/blob/1f36339abc630120047db71c295345649caa364b/src/exec.c#L1095-L1096

## Fix

```c
 if (RV2 <= _inst->operand1 && _inst->operand1 <= RV7) 
   raise_except(ENCODE, "LOADSP", __FILE__, __LINE__); 
```

Additionally, there is a redundant comparison:

https://github.com/yabits/ebcvm/blob/1f36339abc630120047db71c295345649caa364b/src/exec.c#L1098-L1104

`raise_except` will eventually `exit(1)` the application so the second condition is always true.

**Comment by retrage** [comment]
Thank you for opening the issue. I fixed it by changing to the following lines:
https://github.com/yabits/ebcvm/blob/e7a03ee49e855bda2bc547accc76a49958cb9ea0/src/exec.c#L1095-L1099
